import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const externalContracts = {
  10200: {
    DistributionMarket: {
      address: "0x0000000000000000000000000000000000000000",
      abi: [
        { type: "constructor", inputs: [], stateMutability: "nonpayable" },
        { type: "receive", stateMutability: "payable" },
        { type: "function", name: "BASE_FEE_BPS", inputs: [], outputs: [{ name: "", type: "uint256", internalType: "uint256" }], stateMutability: "view" },
        { type: "function", name: "L2_FEE_BPS", inputs: [], outputs: [{ name: "", type: "uint256", internalType: "uint256" }], stateMutability: "view" },
        { type: "function", name: "MAX_PAYOUT_MULTIPLIER", inputs: [], outputs: [{ name: "", type: "uint256", internalType: "uint256" }], stateMutability: "view" },
        { type: "function", name: "REFERENCE_SIGMA", inputs: [], outputs: [{ name: "", type: "uint256", internalType: "uint256" }], stateMutability: "view" },
        { type: "function", name: "addLiquidity", inputs: [{ name: "marketId", type: "uint256", internalType: "uint256" }], outputs: [], stateMutability: "payable" },
        { type: "function", name: "claim", inputs: [{ name: "marketId", type: "uint256", internalType: "uint256" }, { name: "tradeIndex", type: "uint256", internalType: "uint256" }], outputs: [], stateMutability: "nonpayable" },
        { type: "function", name: "claimAll", inputs: [{ name: "marketId", type: "uint256", internalType: "uint256" }], outputs: [], stateMutability: "nonpayable" },
        { type: "function", name: "createMarket", inputs: [{ name: "question", type: "string", internalType: "string" }, { name: "endTime", type: "uint256", internalType: "uint256" }, { name: "mu", type: "int256", internalType: "int256" }, { name: "sigma", type: "uint256", internalType: "uint256" }], outputs: [{ name: "marketId", type: "uint256", internalType: "uint256" }], stateMutability: "payable" },
        { type: "function", name: "getMarket", inputs: [{ name: "marketId", type: "uint256", internalType: "uint256" }], outputs: [{ name: "question", type: "string", internalType: "string" }, { name: "endTime", type: "uint256", internalType: "uint256" }, { name: "resolved", type: "bool", internalType: "bool" }, { name: "outcome", type: "int256", internalType: "int256" }, { name: "currentMu", type: "int256", internalType: "int256" }, { name: "currentSigma", type: "uint256", internalType: "uint256" }, { name: "b", type: "uint256", internalType: "uint256" }, { name: "k", type: "uint256", internalType: "uint256" }, { name: "resolver", type: "address", internalType: "address" }, { name: "accumulatedFees", type: "uint256", internalType: "uint256" }, { name: "tradeCount", type: "uint256", internalType: "uint256" }], stateMutability: "view" },
        { type: "function", name: "getMarketB", inputs: [{ name: "marketId", type: "uint256", internalType: "uint256" }], outputs: [{ name: "", type: "uint256", internalType: "uint256" }], stateMutability: "view" },
        { type: "function", name: "getMarketK", inputs: [{ name: "marketId", type: "uint256", internalType: "uint256" }], outputs: [{ name: "", type: "uint256", internalType: "uint256" }], stateMutability: "view" },
        { type: "function", name: "getMarketSimple", inputs: [{ name: "marketId", type: "uint256", internalType: "uint256" }], outputs: [{ name: "currentMu", type: "int256", internalType: "int256" }, { name: "currentSigma", type: "uint256", internalType: "uint256" }, { name: "b", type: "uint256", internalType: "uint256" }, { name: "k", type: "uint256", internalType: "uint256" }, { name: "resolved", type: "bool", internalType: "bool" }, { name: "outcome", type: "int256", internalType: "int256" }], stateMutability: "view" },
        { type: "function", name: "getTrade", inputs: [{ name: "marketId", type: "uint256", internalType: "uint256" }, { name: "tradeIndex", type: "uint256", internalType: "uint256" }], outputs: [{ name: "trader", type: "address", internalType: "address" }, { name: "prevMu", type: "int256", internalType: "int256" }, { name: "prevSigma", type: "uint256", internalType: "uint256" }, { name: "tradeMu", type: "int256", internalType: "int256" }, { name: "tradeSigma", type: "uint256", internalType: "uint256" }, { name: "collateral", type: "uint256", internalType: "uint256" }, { name: "feePaid", type: "uint256", internalType: "uint256" }, { name: "claimed", type: "bool", internalType: "bool" }], stateMutability: "view" },
        { type: "function", name: "getTradeCount", inputs: [{ name: "marketId", type: "uint256", internalType: "uint256" }], outputs: [{ name: "", type: "uint256", internalType: "uint256" }], stateMutability: "view" },
        { type: "function", name: "getTraderTrades", inputs: [{ name: "marketId", type: "uint256", internalType: "uint256" }, { name: "trader", type: "address", internalType: "address" }], outputs: [{ name: "", type: "uint256[]", internalType: "uint256[]" }], stateMutability: "view" },
        { type: "function", name: "marketCount", inputs: [], outputs: [{ name: "", type: "uint256", internalType: "uint256" }], stateMutability: "view" },
        { type: "function", name: "owner", inputs: [], outputs: [{ name: "", type: "address", internalType: "address" }], stateMutability: "view" },
        { type: "function", name: "resolve", inputs: [{ name: "marketId", type: "uint256", internalType: "uint256" }, { name: "outcome", type: "int256", internalType: "int256" }], outputs: [], stateMutability: "nonpayable" },
        { type: "function", name: "trade", inputs: [{ name: "marketId", type: "uint256", internalType: "uint256" }, { name: "mu", type: "int256", internalType: "int256" }, { name: "sigma", type: "uint256", internalType: "uint256" }], outputs: [], stateMutability: "payable" },
        { type: "function", name: "withdrawFees", inputs: [{ name: "marketId", type: "uint256", internalType: "uint256" }], outputs: [], stateMutability: "nonpayable" },
        { type: "event", name: "FeesWithdrawn", inputs: [{ name: "marketId", type: "uint256", indexed: true, internalType: "uint256" }, { name: "amount", type: "uint256", indexed: false, internalType: "uint256" }], anonymous: false },
        { type: "event", name: "LiquidityAdded", inputs: [{ name: "marketId", type: "uint256", indexed: true, internalType: "uint256" }, { name: "lp", type: "address", indexed: true, internalType: "address" }, { name: "amount", type: "uint256", indexed: false, internalType: "uint256" }, { name: "newB", type: "uint256", indexed: false, internalType: "uint256" }], anonymous: false },
        { type: "event", name: "MarketCreated", inputs: [{ name: "marketId", type: "uint256", indexed: true, internalType: "uint256" }, { name: "question", type: "string", indexed: false, internalType: "string" }, { name: "endTime", type: "uint256", indexed: false, internalType: "uint256" }, { name: "mu", type: "int256", indexed: false, internalType: "int256" }, { name: "sigma", type: "uint256", indexed: false, internalType: "uint256" }, { name: "b", type: "uint256", indexed: false, internalType: "uint256" }], anonymous: false },
        { type: "event", name: "MarketResolved", inputs: [{ name: "marketId", type: "uint256", indexed: true, internalType: "uint256" }, { name: "outcome", type: "int256", indexed: false, internalType: "int256" }], anonymous: false },
        { type: "event", name: "PayoutClaimed", inputs: [{ name: "marketId", type: "uint256", indexed: true, internalType: "uint256" }, { name: "trader", type: "address", indexed: true, internalType: "address" }, { name: "amount", type: "uint256", indexed: false, internalType: "uint256" }], anonymous: false },
        { type: "event", name: "TradeExecuted", inputs: [{ name: "marketId", type: "uint256", indexed: true, internalType: "uint256" }, { name: "trader", type: "address", indexed: true, internalType: "address" }, { name: "tradeIndex", type: "uint256", indexed: false, internalType: "uint256" }, { name: "mu", type: "int256", indexed: false, internalType: "int256" }, { name: "sigma", type: "uint256", indexed: false, internalType: "uint256" }, { name: "collateral", type: "uint256", indexed: false, internalType: "uint256" }, { name: "fee", type: "uint256", indexed: false, internalType: "uint256" }], anonymous: false },
      ],
    },
  },
} as const;

export default externalContracts satisfies GenericContractsDeclaration;
